"""added sequence id table

Revision ID: 2c353724c27d
Revises: b8f3c6492deb
Create Date: 2026-09-23 20:10:24.034792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c353724c27d'
down_revision: Union[str, Sequence[str], None] = 'b8f3c6492deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_category',
               existing_type=postgresql.ENUM('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory'),
               nullable=True)
    op.drop_table('sequence_table')
    # ### end Alembic commands ###
