"""make it nullable the user category

Revision ID: 3a0c7efd63df
Revises: 1a10116446aa
Create Date: 2026-09-29 08:32:20.625768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a0c7efd63df'
down_revision: Union[str, Sequence[str], None] = '1a10116446aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_category',
               existing_type=postgresql.ENUM('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_category',
               existing_type=postgresql.ENUM('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory'),
               nullable=False)
    # ### end Alembic commands ###
