""".1

Revision ID: 40a4617ad99f
Revises: 562a84447d95
Create Date: 2026-10-10 19:08:42.989036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a4617ad99f'
down_revision: Union[str, Sequence[str], None] = '562a84447d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        # Execute raw SQL to add the new value to the Postgres ENUM
        op.execute("ALTER TYPE userstatus ADD VALUE IF NOT EXISTS 'MAPPED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
