""".1

Revision ID: 562a84447d95
Revises: 31f6d72945b2
Create Date: 2026-10-10 18:02:40.400666

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562a84447d95'
down_revision: Union[str, Sequence[str], None] = '31f6d72945b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_details', sa.Column('mother', sa.JSON(), nullable=True))
    op.add_column('family_details', sa.Column('father', sa.JSON(), nullable=True))
    op.add_column('family_details', sa.Column('guardian', sa.JSON(), nullable=True))
    op.add_column('family_details', sa.Column('siblings', sa.JSON(), nullable=True))
    op.drop_column('family_details', 'contact_no')
    op.drop_column('family_details', 'father_name')
    op.drop_column('family_details', 'mother_name')
    op.drop_column('family_details', 'guardian_relation')
    op.drop_column('family_details', 'guardian_name')
    op.add_column('personal_details', sa.Column('is_interested', sa.Boolean(), nullable=True))
    op.alter_column('personal_details', 'lrn_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('subjects', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_unique_constraint('uq_category_subject_code', 'subjects', ['category_id', 'code'])
    op.add_column('user_categories', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_categories_code'), 'user_categories', ['code'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_user_categories_code'), table_name='user_categories')
    op.drop_column('user_categories', 'code')
    op.drop_constraint('uq_category_subject_code', 'subjects', type_='unique')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_column('subjects', 'code')
    op.alter_column('personal_details', 'lrn_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('personal_details', 'is_interested')
    op.add_column('family_details', sa.Column('guardian_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('family_details', sa.Column('guardian_relation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('family_details', sa.Column('mother_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('family_details', sa.Column('father_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('family_details', sa.Column('contact_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('family_details', 'siblings')
    op.drop_column('family_details', 'guardian')
    op.drop_column('family_details', 'father')
    op.drop_column('family_details', 'mother')
    # ### end Alembic commands ###
