"""setup

Revision ID: 608528a53d29
Revises: 
Create Date: 2026-10-03 12:37:37.904747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '608528a53d29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('teacher_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('suffix', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'EMPLOYEE', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('user_category', sa.Enum('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'COMPLETED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('assessments',
    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teacher_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_category', sa.Enum('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory'), nullable=True),
    sa.Column('assessment_type', sa.Enum('ACTIVITY', 'QUIZ', 'EXAM', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_assessments_assessment_id'), 'assessments', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessments_assessment_type'), 'assessments', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_index(op.f('ix_assessments_subject_code'), 'assessments', ['subject_code'], unique=False)
    op.create_index(op.f('ix_assessments_target_category'), 'assessments', ['target_category'], unique=False)
    op.create_index(op.f('ix_assessments_teacher_id'), 'assessments', ['teacher_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teacher_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strand_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'DRAFT', name='recordstatus'), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('present_count', sa.Integer(), nullable=False),
    sa.Column('absent_count', sa.Integer(), nullable=False),
    sa.Column('excused_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.teacher_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_attendance_sessions_level_code'), 'attendance_sessions', ['level_code'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_date'), 'attendance_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_id'), 'attendance_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_strand_code'), 'attendance_sessions', ['strand_code'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_teacher_id'), 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_table('contact_details',
    sa.Column('contact_details_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('street_building_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('municipality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_details_id')
    )
    op.create_index(op.f('ix_contact_details_contact_details_id'), 'contact_details', ['contact_details_id'], unique=False)
    op.create_index(op.f('ix_contact_details_user_id'), 'contact_details', ['user_id'], unique=False)
    op.create_table('family_details',
    sa.Column('family_details_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mother_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_relation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('family_details_id')
    )
    op.create_index(op.f('ix_family_details_family_details_id'), 'family_details', ['family_details_id'], unique=False)
    op.create_index(op.f('ix_family_details_user_id'), 'family_details', ['user_id'], unique=False)
    op.create_table('personal_details',
    sa.Column('personal_details_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('civil_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('religion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lrn_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('personal_details_id')
    )
    op.create_index(op.f('ix_personal_details_lrn_number'), 'personal_details', ['lrn_number'], unique=False)
    op.create_index(op.f('ix_personal_details_personal_details_id'), 'personal_details', ['personal_details_id'], unique=False)
    op.create_index(op.f('ix_personal_details_student_id'), 'personal_details', ['student_id'], unique=False)
    op.create_index(op.f('ix_personal_details_user_id'), 'personal_details', ['user_id'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('assessment_materials',
    sa.Column('material_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index(op.f('ix_assessment_materials_assessment_id'), 'assessment_materials', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_materials_material_id'), 'assessment_materials', ['material_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('question_set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categories_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('total_pool_items', sa.Integer(), nullable=False),
    sa.Column('total_required_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ),
    sa.PrimaryKeyConstraint('question_set_id')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_assessment_questions_question_set_id'), 'assessment_questions', ['question_set_id'], unique=False)
    op.create_table('assessment_submissions',
    sa.Column('submission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_category', sa.Enum('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory'), nullable=True),
    sa.Column('answers_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('attachments_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('auto_score', sa.Float(), nullable=False),
    sa.Column('manual_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'GRADED', name='submissionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_assessment_submissions_assessment_id'), 'assessment_submissions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_student_id'), 'assessment_submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_submission_id'), 'assessment_submissions', ['submission_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_session_student')
    )
    op.create_index(op.f('ix_attendance_records_record_id'), 'attendance_records', ['record_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_record_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_assessment_submissions_submission_id'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_student_id'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_assessment_id'), table_name='assessment_submissions')
    op.drop_table('assessment_submissions')
    op.drop_index(op.f('ix_assessment_questions_question_set_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_assessment_materials_material_id'), table_name='assessment_materials')
    op.drop_index(op.f('ix_assessment_materials_assessment_id'), table_name='assessment_materials')
    op.drop_table('assessment_materials')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_personal_details_user_id'), table_name='personal_details')
    op.drop_index(op.f('ix_personal_details_student_id'), table_name='personal_details')
    op.drop_index(op.f('ix_personal_details_personal_details_id'), table_name='personal_details')
    op.drop_index(op.f('ix_personal_details_lrn_number'), table_name='personal_details')
    op.drop_table('personal_details')
    op.drop_index(op.f('ix_family_details_user_id'), table_name='family_details')
    op.drop_index(op.f('ix_family_details_family_details_id'), table_name='family_details')
    op.drop_table('family_details')
    op.drop_index(op.f('ix_contact_details_user_id'), table_name='contact_details')
    op.drop_index(op.f('ix_contact_details_contact_details_id'), table_name='contact_details')
    op.drop_table('contact_details')
    op.drop_index(op.f('ix_attendance_sessions_teacher_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_strand_code'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_date'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_level_code'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_assessments_teacher_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_target_category'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_subject_code'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_type'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sequence_table')
    # ### end Alembic commands ###
