"""added on delete cascade

Revision ID: 964fe6d1766b
Revises: aa88dafb583f
Create Date: 2026-09-29 07:01:53.945564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964fe6d1766b'
down_revision: Union[str, Sequence[str], None] = 'aa88dafb583f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contact_details_user_id_fkey'), 'contact_details', type_='foreignkey')
    op.create_foreign_key(None, 'contact_details', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('family_details_user_id_fkey'), 'family_details', type_='foreignkey')
    op.create_foreign_key(None, 'family_details', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('personal_details_user_id_fkey'), 'personal_details', type_='foreignkey')
    op.create_foreign_key(None, 'personal_details', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'personal_details', type_='foreignkey')
    op.create_foreign_key(op.f('personal_details_user_id_fkey'), 'personal_details', 'users', ['user_id'], ['user_id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'family_details', type_='foreignkey')
    op.create_foreign_key(op.f('family_details_user_id_fkey'), 'family_details', 'users', ['user_id'], ['user_id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'contact_details', type_='foreignkey')
    op.create_foreign_key(op.f('contact_details_user_id_fkey'), 'contact_details', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
