"""change col name for teacher id

Revision ID: aa88dafb583f
Revises: e2f293ad6f0b
Create Date: 2026-09-28 22:32:12.988231

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa88dafb583f'
down_revision: Union[str, Sequence[str], None] = 'e2f293ad6f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TYPE IF EXISTS recordstatus;")
    op.execute("DROP TYPE IF EXISTS attendancestatus;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
                    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('teacher_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('level_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('strand_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('session_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('display_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('status', sa.Enum('COMPLETED', 'DRAFT', name='recordstatus'), nullable=False),
                    sa.Column('total_count', sa.Integer(), nullable=False),
                    sa.Column('present_count', sa.Integer(), nullable=False),
                    sa.Column('absent_count', sa.Integer(), nullable=False),
                    sa.Column('excused_count', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['teacher_id'], ['users.teacher_id'], ),
                    sa.PrimaryKeyConstraint('session_id')
                    )
    op.create_index(op.f('ix_attendance_sessions_level_code'), 'attendance_sessions', ['level_code'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_date'), 'attendance_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_id'), 'attendance_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_strand_code'), 'attendance_sessions', ['strand_code'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_teacher_id'), 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_session_student')
    )
    op.create_index(op.f('ix_attendance_records_record_id'), 'attendance_records', ['record_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_record_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_attendance_sessions_teacher_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_strand_code'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_date'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_level_code'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
