"""added assessments

Revision ID: afddd96d8d50
Revises: 3a0c7efd63df
Create Date: 2026-10-02 17:22:59.236944

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision: str = 'afddd96d8d50'
down_revision: Union[str, Sequence[str], None] = '3a0c7efd63df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teacher_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_category', postgresql.ENUM('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory',create_type=False), nullable=True),
    sa.Column('assessment_type', sa.Enum('ACTIVITY', 'QUIZ', 'EXAM', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_assessments_assessment_id'), 'assessments', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessments_assessment_type'), 'assessments', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_index(op.f('ix_assessments_subject_code'), 'assessments', ['subject_code'], unique=False)
    op.create_index(op.f('ix_assessments_target_category'), 'assessments', ['target_category'], unique=False)
    op.create_index(op.f('ix_assessments_teacher_id'), 'assessments', ['teacher_id'], unique=False)
    op.create_table('assessment_materials',
    sa.Column('material_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index(op.f('ix_assessment_materials_assessment_id'), 'assessment_materials', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_materials_material_id'), 'assessment_materials', ['material_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('question_set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categories_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('total_pool_items', sa.Integer(), nullable=False),
    sa.Column('total_required_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ),
    sa.PrimaryKeyConstraint('question_set_id')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_assessment_questions_question_set_id'), 'assessment_questions', ['question_set_id'], unique=False)
    op.create_table('assessment_submissions',
                    sa.Column('submission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('assessment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('student_category', postgresql.ENUM('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory',create_type=False), nullable=True),
                    sa.Column('answers_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
                    sa.Column('attachments_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
                    sa.Column('auto_score', sa.Float(), nullable=False),
                    sa.Column('manual_score', sa.Float(), nullable=False),
                    sa.Column('final_score', sa.Float(), nullable=False),
                    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('is_late', sa.Boolean(), nullable=False),
                    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'GRADED', name='submissionstatus'), nullable=False),
                    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('submission_id')
                    )
    op.create_index(op.f('ix_assessment_submissions_assessment_id'), 'assessment_submissions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_student_id'), 'assessment_submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessment_submissions_submission_id'), 'assessment_submissions', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_submissions_submission_id'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_student_id'), table_name='assessment_submissions')
    op.drop_index(op.f('ix_assessment_submissions_assessment_id'), table_name='assessment_submissions')
    op.drop_table('assessment_submissions')
    op.drop_index(op.f('ix_assessment_questions_question_set_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_assessment_materials_material_id'), table_name='assessment_materials')
    op.drop_index(op.f('ix_assessment_materials_assessment_id'), table_name='assessment_materials')
    op.drop_table('assessment_materials')
    op.drop_index(op.f('ix_assessments_teacher_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_target_category'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_subject_code'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_type'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
