"""added user category

Revision ID: b8f3c6492deb
Revises: 936188098986
Create Date: 2026-09-23 13:44:01.879681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8f3c6492deb'
down_revision: Union[str, Sequence[str], None] = '936188098986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    usercategory_enum = postgresql.ENUM('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory')
    usercategory_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_category', sa.Enum('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_category')
    # ### end Alembic commands ###
