"""added firebase_uid

Revision ID: f35922419c55
Revises: 2c353724c27d
Create Date: 2026-09-24 11:30:57.285809

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f35922419c55'
down_revision: Union[str, Sequence[str], None] = '2c353724c27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('users', 'user_category',
               existing_type=postgresql.ENUM('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory'),
               nullable=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.alter_column('users', 'user_category',
               existing_type=postgresql.ENUM('ELEMENTARY', 'SECONDARY', 'BLP', name='usercategory'),
               nullable=True)
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###
